"""
Media Handler Configuration for Game
Copyright (c) 2018 Jared Daniel Carbonell Recomendable.

Licensed under the GNU General Public License (GPL) Version 3.
"""

# GRAPHICS
## GLOBAL SPRITE SPECIFICATIONS
SPR_GLOBAL_WIDTH      = 32  # also set the x_grid for the level
SPR_GLOBAL_HEIGHT     = 32  # also set the y_grid for the level

## PLAYER SPRITE LOCATIONS
SPR_PLAYER_BACK_STA   = (  0,   0)
SPR_PLAYER_FRONT_STA  = ( 96,   0)
SPR_PLAYER_LEFT_STA   = ( 64,   0)
SPR_PLAYER_RIGHT_STA  = ( 32,   0)
SPR_PLAYER_BACK_WA1   = (  0,  32)
SPR_PLAYER_BACK_WA2   = (  0,  64)
SPR_PLAYER_FRONT_WA1  = ( 96,  32)
SPR_PLAYER_FRONT_WA2  = ( 96,  64)
SPR_PLAYER_LEFT_WA1   = ( 64,  32)
SPR_PLAYER_LEFT_WA2   = ( 64,  64)
SPR_PLAYER_RIGHT_WA1  = ( 32,  32)
SPR_PLAYER_RIGHT_WA2  = ( 32,  64)
SPR_PLAYER_IMAGES = (
    (SPR_PLAYER_BACK_STA,),
    (SPR_PLAYER_FRONT_STA,),
    (SPR_PLAYER_LEFT_STA,),
    (SPR_PLAYER_RIGHT_STA,),
    (SPR_PLAYER_BACK_WA1, SPR_PLAYER_BACK_WA2),
    (SPR_PLAYER_FRONT_WA1, SPR_PLAYER_FRONT_WA2),
    (SPR_PLAYER_LEFT_WA1, SPR_PLAYER_LEFT_WA2),
    (SPR_PLAYER_RIGHT_WA1, SPR_PLAYER_RIGHT_WA2)
)

## BOMB SPRITE LOCATIONS
SPR_BOMB_100          = (  0,  96)
SPR_BOMB_75           = ( 32,  96)
SPR_BOMB_50           = ( 64,  96)
SPR_BOMB_25           = ( 96,  96)

## FLOOR SPRITE LOCATIONS
SPR_FLOOR_GEN         = ( 96, 128)
SPR_FLOOR_SRC         = ( 32, 128)
SPR_FLOOR_DES         = ( 64, 128)

## WALL SPRITE LOCATIONS
SPR_WALL              = (  0, 128)

## MONSTER SPRITE LOCATIONS
SPR_MONSTER_BACK_STA  = (  0, 160)
SPR_MONSTER_FRONT_STA = ( 96, 160)
SPR_MONSTER_LEFT_STA  = ( 32, 160)
SPR_MONSTER_RIGHT_STA = ( 64, 160)
SPR_MONSTER_BACK_WA1  = (  0, 160)
SPR_MONSTER_BACK_WA2  = (  0, 192)
SPR_MONSTER_FRONT_WA1 = ( 96, 160)
SPR_MONSTER_FRONT_WA2 = ( 96, 192)
SPR_MONSTER_LEFT_WA1  = ( 64, 160)
SPR_MONSTER_LEFT_WA2  = ( 64, 192)
SPR_MONSTER_RIGHT_WA1 = ( 32, 160)
SPR_MONSTER_RIGHT_WA2 = ( 32, 192)
SPR_MONSTER_IMAGES = (
    (SPR_MONSTER_BACK_STA,),
    (SPR_MONSTER_FRONT_STA,),
    (SPR_MONSTER_LEFT_STA,),
    (SPR_MONSTER_RIGHT_STA,),
    (SPR_MONSTER_BACK_WA1, SPR_MONSTER_BACK_WA2),
    (SPR_MONSTER_FRONT_WA1, SPR_MONSTER_FRONT_WA2),
    (SPR_MONSTER_LEFT_WA1, SPR_MONSTER_LEFT_WA2),
    (SPR_MONSTER_RIGHT_WA1, SPR_MONSTER_RIGHT_WA2)
)
