"""
Level 2 Objects
Copyright (c) 2018 Jared Daniel Carbonell Recomendable.

Licensed under the GNU General Public License (GPL) Version 3.
"""

LEVEL = (
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
    "WWFFFFFFFFFFFFWW",
    "WWFWWFWWWWFWWFWW",
    "WWFWWFWWWWFWWFWW",
    "WSFFFFFFFFFFFFDW",
    "WWFWWFWWWWFWWFWW",
    "WWFWWFWWWWFWWFWW",
    "WWFFFFFFFFFFFFWW",
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWW",
)

PLAYER_INITIAL_X         = 1
PLAYER_INITIAL_Y         = 7
PLAYER_INITIAL_DIRECTION = 3

MONSTERS_HORIZONTAL = (
    ( 2,  4, 3),
    (13, 10, 2),
)

MONSTERS_VERTICAL = (
    ( 2, 10, 0),
    ( 5,  4, 1),
    (10, 10, 0),
    (13,  4, 1),
)
